/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { useState } from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import ArtText from "react-native-remote-font";

const App = () => {
  const [fontInfoIndex, setFontInfoIndex] = useState(0);

  return (
    <View style={{ flex: 1, paddingTop: 100, paddingLeft: 20 }}>
      <TouchableOpacity
        style={{
          padding: 10,
          backgroundColor: "pink",
          width: 100,
          alignItems: "center",
        }}
        onPress={() => {
          setFontInfoIndex((fontInfoIndex + 1) % fontInfoList.length);
        }}
      >
        <Text>{"Switch Font"}</Text>
      </TouchableOpacity>
      <Text style={{ marginVertical: 20 }}>
        {"Current font - " +
          fontInfoIndex +
          " - " +
          fontInfoList[fontInfoIndex].fontName}
      </Text>

      <ArtText
        text="Hello World"
        style={{ fontSize: 20, fontVariant: ["proportional-nums"] }}
        fontInfo={fontInfoList[fontInfoIndex]}
      />
    </View>
  );
}

export default App;


const fontInfoList = [
  {
    fontName: "Ma Shan Zheng",
    fontUrl: "https://fonts.gstatic.com/s/mashanzheng/v10/NaPecZTRCLxvwo41b4gvzkXaRMHsCoRTJKKTqxFXqIji1hn3wSpSEA3eSpJy0awdsFt2Zfc6SSE.119.woff2",
  },
  {
    fontName: "Afacad",
    fontUrl: "https://fonts.gstatic.com/s/afacad/v1/6NUI8FKMIQOGaw6ahLYEvBjUVG5Ga92uVSQ-9kKlZfNfuw.ttf",
  },
  {
    fontName: "Rubik Bubbles",
    fontUrl:
      "https://fonts.gstatic.com/s/rubikbubbles/v3/JIA1UVdwbHFJtwA7Us1BPFbRNTENfDxyRXI.ttf",
  },
  {
    fontName: "Preahvihear",
    fontUrl: "https://fonts.gstatic.com/s/preahvihear/v29/6NUS8F-dNQeEYhzj7uluxswE49FJf8Wv.ttf",
  },
];

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
